{
 "title": "Kubernetes / cAdvisor Monitoring",
 "description": "Kubernetes Pod Resource Overview. node-exporter and kubelet-cadvisor required.",
 "tags": [
  "kubernetes",
  "cadvisor"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Node",
    "query": {
     "query": "label_values(machine_memory_bytes, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Memory Usage %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{instance=~\"$instance\",pod!=\"\"}) / sum(machine_memory_bytes{instance=~\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "Node CPU Usage % (1m avg)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\",instance=~\"$instance\"}[1m])) / sum(machine_cpu_cores{instance=~\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "Node Filesystem Usage %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{instance=~\"$instance\",device=~\"/dev/.*\"}) - sum(node_filesystem_avail_bytes{instance=~\"$instance\",device=~\"/dev/.*\"})) / sum(node_filesystem_size_bytes{instance=~\"$instance\",device=~\"/dev/.*\"}) * 100"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pods CPU Usage (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",pod!=\"\",instance=~\"$instance\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Containers CPU Usage (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",container!=\"\",pod!=\"\",instance=~\"$instance\"}[5m])) by (pod, container)",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Pods Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",pod!=\"\",instance=~\"$instance\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Containers Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",container!=\"POD\",container!=\"\",pod!=\"\",instance=~\"$instance\"}) by (pod, container)",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  { "title": "Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Pods Network I/O (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod!=\"\",instance=~\"$instance\"}[5m])) by (pod)",
     "legendFormat": "RX {{pod}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod!=\"\",instance=~\"$instance\"}[5m])) by (pod)",
     "legendFormat": "TX {{pod}}"
    }
   ]
  },
  {
   "title": "Containers Network I/O (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container!=\"POD\",container!=\"\",pod!=\"\",instance=~\"$instance\"}[5m])) by (pod, container)",
     "legendFormat": "RX {{pod}}/{{container}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container!=\"POD\",container!=\"\",pod!=\"\",instance=~\"$instance\"}[5m])) by (pod, container)",
     "legendFormat": "TX {{pod}}/{{container}}"
    }
   ]
  }
 ]
}